FROM yujioshima/dynet:base-gpu-in-c

# DyNet, version 4234759
ENV DYNET_VERSION 4234759
RUN cd /opt && \
        git clone https://github.com/clab/dynet.git && \
        cd dynet && \
        git checkout ${DYNET_VERSION} && \
        sed -i -e '/^#/!s/ -march=native//g' CMakeLists.txt && \
        mkdir build && \
        cd build && \
        cmake .. -DEIGEN3_INCLUDE_DIR=/opt/eigen -DBACKEND=cuda && \
        make -j16 install
WORKDIR /opt/dynet
